[1,"\u001B[0m\u001B[1m\u001B[31merror\u001B[0m: Uncaught Error: Project _quarto.yml validation failed.\n\nIn file _quarto.yml\n(line 9, columns 3--7) property name \u001B[34mlogo\u001B[39m is invalid\n 8: \u001B[34m  date: \"4/5/2024\"\u001B[39m\n 9: \u001B[34m  logo: \"icon.png\"\u001B[39m\n     ~~~~~\n10: \u001B[34m  chapters:\u001B[39m\n\u001B[34mâ„¹\u001B[39m The error happened in location \u001B[34mbook\u001B[39m:\u001B[34mlogo\u001B[39m.\n\n        throw new ValidationError2(errorMessage, yamlValidationErrors);\n\u001B[0m\u001B[31m              ^\u001B[0m\n    at \u001B[0m\u001B[1m\u001B[3mreadAndValidateYamlFromFile\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m42120\u001B[0m:\u001B[0m\u001B[33m15\u001B[0m)\n    at async \u001B[0m\u001B[36mfile:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m82873\u001B[0m:\u001B[0m\u001B[33m26\u001B[0m\n    at async \u001B[0m\u001B[1m\u001B[3mprojectContext\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m82725\u001B[0m:\u001B[0m\u001B[33m26\u001B[0m)\n    at async \u001B[0m\u001B[1m\u001B[3mrender\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m90657\u001B[0m:\u001B[0m\u001B[33m21\u001B[0m)\n"]
